### ISSUE TITLE
url  参数分隔符写错了吧

### ISSUE THREAD

**Issue by newpost** [wangdoc/html-tutorial#1]
&

**Comment by FrankFang** [comment]
Just make a pull request!

**Comment by FrankFang** [comment]
另外，ryf 没错，你这个符号是查询参数分隔符。请 close

**Comment by newpost** [comment]
@FrankFang 给个链接,谢谢.

**Comment by ruanyf** [comment]
谢谢指出，我改过了。

不过，`;`确实可以做参数分隔符，参见[维基百科](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax)。我刚才把 Google 查询分隔符从`&`改成`;`，可以正常执行。

**Comment by ruanyf** [comment]
刚才写错了，又试了一下，Google 也不能用`;`替换`&`，作为查询分隔符。
