### ISSUE TITLE
HTML教程文本标签中<ruby>，<rp>内容介绍有点儿歧义

### ISSUE THREAD

**Issue by XiaoLongRenMengXin** [wangdoc/html-tutorial#11]
### 首先感谢您的辛勤付出！

[https://wangdoc.com/html/text.html#ruby%EF%BC%8Crp](url)
在学习中，rp标签只是一个起始和结束的符号在其中写入内容是不显示的，所以在代码`<ruby>
汉<rp>(</rp><rt>han</rt><rp>)</rp>
字<rp>(</rp><rt>zi</rt><rp>)</rp>
</ruby>`的渲染结果中是不显示”()“建议优化一下`<ruby>
汉<rp><rt>(han</rt></rp>
字<rp><rt>zi)</rt></rp>
</ruby>`

**Comment by ruanyf** [comment]
谢谢指出，原文是错的。我重写了这个部分。
