### ISSUE TITLE
文本描述存在一定的歧义

### ISSUE THREAD

**Issue by XiaoLongRenMengXin** [wangdoc/html-tutorial#12]
### 首先感谢您的辛勤付出！

[https://wangdoc.com/html/image.html#figure%EF%BC%8Cfigcaption](url)，文中提到`<figcaption>`是`<fingure>`可选的子元素，表示图像的标题。事实上显示的结果并不那么的明显，更像是对img图标的补充性说明的容器，另外可以多次重复出现，渲染效果具备高亮、突出的状态，而“标题”显的过于谨慎，仿佛具有唯一性类似“title”，不可重复使用，个人建议修改为`<figcaption>`是`<fingure>`可选的子元素，在标签内可重复出现，用于对图像或者语句的文本描述，具有高亮、突出的渲染效果。

最后代码中的`figcaption`标签建议可以放在`<img>`或者`<p>`之前，比较美观

**Comment by ruanyf** [comment]
谢谢指出，已经修改。
