### ISSUE TITLE
优化小建议

### ISSUE THREAD

**Issue by XiaoLongRenMengXin** [wangdoc/html-tutorial#13]
### 首先感谢您的付出！
[http://wangdoc.com/html/table.html#th%EF%BC%8Ctd](url) 关于scope属性介绍，我学习后发现rowgroup-rowspan、colgroup-colspan对应配合使用比较容易理解，推荐可以在每个属性后提示一下呢

> <table border="1">
        <tr>
            <th scope="rowgroup" rowspan="2">部门</th>
            <th scope="rowgroup" rowspan="2">学徒</th>
            <th scope="colgroup" colspan="2">武功熟练度</th>
        </tr>
        <tr>
            <th scope="col">乾坤大挪移</th>
            <th scope="col">北冥神功</th>
        </tr>
        <tr>
            <th scope="rowgroup" rowspan="2">功夫部</th>
            <td>张无忌</td>
            <td>80%</td>
            <td>70%</td>
        </tr>
        <tr>
            <td>张三丰</td>
            <td>100%</td>
            <td>100%</td>
        </tr>
    </table>

**Comment by ruanyf** [comment]
谢谢指出，已经补上例子。https://github.com/wangdoc/html-tutorial/commit/54a3dc59c51b98dd99b1a0762329f7b4648646ff
