### ISSUE TITLE
"<meta> 标签的 http-equiv 属性覆盖 HTTP 回应的头信息字段" 说法不妥

### ISSUE THREAD

**Issue by junyiz** [wangdoc/html-tutorial#32]
> When the http-equiv attribute is specified on a meta element, the element is a pragma directive. You can use this element to simulate an HTTP response header, but only if the server doesn't send the corresponding real header; you can't override an HTTP header with a meta http-equiv element.

从 [W3C](https://www.w3.org/wiki/HTML/Elements/meta?iframe=true&width=100%25&height=100%25) 的对 http-equiv 如上定义来看，如下的覆盖的说法不妥

> <meta>标签的http-equiv属性用来覆盖 HTTP 回应的头信息字段

**Comment by ruanyf** [comment]
谢谢指出，已经更正。
