### ISSUE TITLE
文章中的文字有错误

### ISSUE THREAD

**Issue by suzhenghui-sky** [wangdoc/html-tutorial#34]
HTML 语言简介 ---> 2.网页的基本概念  --->>>2.0标签 --->>标签放在一对尖括号里面（比如<title>），大多数标签都是成对出现的，分成开始标签和结束标签，结束标签在标签名之前加斜杠（比如</title>）。但是，也有一些标签不是成对使用，而是只有开始标签，没有结束标签，比如上一节示例的<meta>标签。 哪里来的“上一节示例<meta>标签”；这是不是开始吗？

**Comment by ruanyf** [comment]
不是写了示例为`<meta>`标签吗
