### ISSUE TITLE
html教程中的一个小问题

### ISSUE THREAD

**Issue by Hoffconna** [wangdoc/html-tutorial#4]
html教程中元素的属性教程中，2.4 tapindex 的示例代码

<p tabindex="0">这段文字可以获得焦点。</div> 

好像标签写错了，结尾好像是</p>不是</div>

链接为
https://wangdoc.com/html/attribute.html

**Comment by Hoffconna** [comment]
我佛了，github吞标签 大概就是 示例代码结尾的div标签应该换为p标签

**Comment by ruanyf** [comment]
谢谢指出，已经修正。
